#!/bin/bash
date
./bondlength_histogram.py  O Cu >& BVSCu
echo PNG file for Cu part of Fig.5 generated
date

./bondlength_histogram.py  O V  >& BVSV
echo PNG file for V part of Fig.5 generated
date

./bondlength_histogram.py  O Fe >& BVSFe
echo PNG file for Fe part of Fig.5 generated
date
