#!/bin/bash
date

./bondlength_histogram.py N
echo PNG file for N generated
data

./bondlength_histogram.py F
echo PNG file for F generated
data

./bondlength_histogram.py O
echo PNG file for O generated
data

echo followings require two args


./bondlength_histogram.py  O Cu
echo PNG file for Cu part of Fig.5 generated
date

./bondlength_histogram.py  O V
echo PNG file for V part of Fig.5 generated
date

./bondlength_histogram.py  O Fe
echo PNG file for Fe part of Fig.5 generated
date
